Basic page routing with authentication
petrarchy/arctype pull request #4
Opened 2016-12-15 21:39 UTC by zelitzsi

This changeset adds a login page that moves to a main page when login is successful. The main page has a logout button that destroys the user session. Authentication is done by running an auth query on pages that require login to access. Unsuccessful logins do not result in a page transition.

All page routing is done on the dev server only for development purposes.

2016-12-19 19:12 UTC, jessemao commented on server/index.js
> +app.post('/logout', async (req, res) => {
prefer to use `app.get()` here. I don't recommend to use `res.redirect` with `post`, could cause some trouble, like AJAX `post` would not redirect to target page.

2016-12-19 19:13 UTC, jessemao commented on src/Login/action_types.js
> +export const USERNAME = 'LOGIN_USERNAME';
what's the purpose of this change?

2016-12-19 19:13 UTC, jessemao commented on src/Login/actions.js
> +        console.log('auth test: ', data.auth);
remove

2016-12-19 19:14 UTC, jessemao commented on src/Register/actions.js
> +        console.log('res: ', data);
remove

2017-02-09 22:14 UTC, zelitzsi commented on src/Login/action_types.js
> +export const USERNAME = 'LOGIN_USERNAME';
When I do that, it doesn't even compile. In ES6, your exports must either be named or be the default export.

2017-02-09 22:26 UTC, dennismphil commented on server/index.js
> +app.get('*', (req, res) => {
Since this is a wildcard, we should keep this at the end of the file, below all `app.get`'s

2017-02-09 22:32 UTC, dennismphil commented on server/index.js
> +    res.sendFile(path.join(__dirname, 'index.html'));
It might be worth checking if the header accepts html before serving an html

2017-02-09 22:40 UTC, dennismphil commented on src/Login/actions.js
> +            window.location = '/main';
If you directly manipulate the window.location we will lose the browser history. Instead, you could use React router's `browserHistory`

`browserHistory.push('/main')`;

2017-02-09 23:14 UTC, dennismphil commented on src/dev_routing.js
> +    const data = await query({query: '{ auth }'});
In a single page app, we shouldn't need to check with the server before transition. This is fundamentally broken.

2017-02-09 23:19 UTC, dennismphil commented on src/dev_routing.js
> +    window.location = '/login';
we should not directly manipulate the urls.

2017-02-09 23:19 UTC, dennismphil requested changes
dev_routing file needs some changes

2017-02-20 23:25 UTC, dennismphil approved these changes

2017-02-20 23:46 UTC, merged